project_id: pebolas-sandbox
location: southamerica-east1


pipeline:
  name: titanic-pipeline
  root: gs://sample-model-kubeflow-pipeline/
  description: "Pipeline to preprocess Titanic dataset"
  package_path: titanic_pipeline.json
  


parameters:
  porject_id: pebolas-sandbox
  dataset_id: titanic
  table_id: train_data
  output_table_id: train_cleaned
  dataset_display_name: titanic


packages:
  BIGQUERY: google-cloud-bigquery==3.26.0
  PANDAS: pandas==2.2.3
  DB_TYPES: db-dtypes==1.3.0
  SKLEARN: scikit-learn==1.5.2
  AIPLATFORM: google-cloud-aiplatform==1.69.0