artifacts_root: artifacts

gcp_config:
  project_id: 'pebolas-sandbox'
  bucket_name: 'pebolas-sandbox'

bigquery_connector:
  root_dir: artifacts/bigquery_connector
  data_file: data.csv
  dataset_id: 'titanic'
  table_id: 'train_data'
  output_table_id: 'train_data_cleaned'


data_preprocessor:
  root_dir: artifacts/data_preprocessor
  scaler_file: scaler.pkl
  postprocessed_data_file: data.csv

bucket_connector: 
  bucket_name: sample-model-train-stack-files
  scaler_gcs_path: preprocessing/scaler.pkl