steps:

  - name: '${_SERVICE_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_API_NAME}/${_IMAGE_NAME}:latest'
    entrypoint: bash
    args:
      - -c
      - |
        jupyter nbconvert --execute --to notebook --inplace 'stacks/${_PIPELINE_NAME}/${_PIPELINE_NAME}.ipynb'
images:
  - '${_SERVICE_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_API_NAME}/${_IMAGE_NAME}:latest'
options:
  logging: CLOUD_LOGGING_ONLY
